name: pansy
description: A unoffical pixiv client.

publish_to: 'none'

version: 0.0.9+9


environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  rust_lib_pansy:
    path: rust_builder
  flutter_rust_bridge: 2.11.1
  intl: ^0.19.0
  file_picker: ^10.2.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  waterfall_flow: ^3.1.1
  flutter_staggered_grid_view: ^0.7.0
  decorated_icon: ^1.2.1
  isolate: ^2.1.1
  extended_image: ^10.0.1
  date_format: ^2.0.9
  event: ^3.1.0
  flutter_styled_toast: ^2.2.1
  filesystem_picker: ^4.1.0
  url_launcher: ^6.3.1
  flutter_inappwebview: ^6.1.5
  clipboard: ^0.1.3
  app_links: ^6.4.0
  signals_flutter: ^6.0.0
  share_plus: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - lib/assets/
